### ISSUE TITLE
Implement a "play task" button in the backend task list view

### ISSUE THREAD

**Issue by bembelimen** [joomla-projects/soc21_website-cronjob#18]
### Describe the solution you'd like
The admin should be able to run (published and unpublished) tasks directly from the backend by clicking a button in the list view of the scheduler component.
- [x] Implemented a test run permission on task level
- [x] Implemented a plugin entry point
- [x] Extend the list view to show a play button
- [x] Output the result in an info box

**Comment by ditsuke** [comment]
Closed by #33
